title: Rashon Poole
logo: /assets/img/rashon_poole.JPG
description: PhD Student in Electrical Engineering and Computer Science Department, University of Michigan Ann Arbor
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
